export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import { DM_Sans } from "next/font/google";
import { ThemeProvider } from "@/components/darkmode";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import AuthProvider from "@/provider/auth";
const font = DM_Sans({ subsets: ["latin"] });
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={font.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            {children}
            <Toaster />
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
